@startuml
class Usuario{
 -numero: int
 -nombre: String
 -contactos: Usuario[]
 -historial: Historial[]
} 

class Historial{
 historial: Mensaje[]
 usuario1: Usuario
 usuario2: Usuario
}

class Mensaje{
 -emisor: Usuario
 -receptor: Usuario
 -texto: String
}

Usuario "2" o- "1" Historial

Historial "1" o- "*" Mensaje

Usuario "1" o- "*" Mensaje

@enduml